<<<<<<< HEAD
﻿services:
  postgres:
    image: postgres:15
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
=======
version: "3.9"
>>>>>>> 57fd1ac57de36b7b97d4eaca18d216063a956533

services:

  backend:
    build: ./backend/backend
    container_name: spring-backend
    restart: always
    ports:
      - "8080:8080"
<<<<<<< HEAD
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_FLYWAY_URL: ${FLYWAY_URL}
      SPRING_FLYWAY_USER: ${FLYWAY_USER}
      SPRING_FLYWAY_PASSWORD: ${FLYWAY_PASSWORD}
      SPRING_REDIS_HOST: ${REDIS_HOST}
      SPRING_REDIS_PORT: ${REDIS_PORT}
      SPRING_REDIS_PASSWORD: ${REDIS_PASSWORD}
      AWS_S3_ACCESS_KEY: ${AWS_S3_ACCESS_KEY}
      AWS_S3_SECRET_KEY: ${AWS_S3_SECRET_KEY}
      AWS_S3_REGION: ${AWS_S3_REGION}
      AWS_S3_BUCKET: ${AWS_S3_BUCKET}
      AWS_SES_ACCESS_KEY: ${AWS_SES_ACCESS_KEY}
      AWS_SES_SECRET_KEY: ${AWS_SES_SECRET_KEY}
      AWS_SES_REGION: ${AWS_SES_REGION}
      SES_FROM_EMAIL: ${SES_FROM_EMAIL}

  frontend:
    build: ./frontend
    ports:
      - "3000:80"

volumes:
  pgdata:
=======
    env_file:
      - .env
>>>>>>> 57fd1ac57de36b7b97d4eaca18d216063a956533
