// Mock data for users with different roles
export const mockUsers = [
  {
    id: 1,
    username: "admin",
    email: "admin@ims.com",
    password: "admin123",
    role: "Admin",
    status: "Active",
    fullName: "System Administrator",
    createdAt: "2025-01-01",
  },
  {
    id: 2,
    username: "sales.user",
    email: "sales@ims.com",
    password: "sales123",
    role: "Sales",
    status: "Active",
    fullName: "Sales User",
    createdAt: "2025-01-05",
  },
  {
    id: 3,
    username: "planner.user",
    email: "planner@ims.com",
    password: "planner123",
    role: "Planner",
    status: "Active",
    fullName: "Planner User",
    createdAt: "2025-01-10",
  },
  {
    id: 4,
    username: "manager.user",
    email: "manager@ims.com",
    password: "manager123",
    role: "Manager",
    status: "Active",
    fullName: "Manager User",
    createdAt: "2025-01-15",
  },
  {
    id: 5,
    username: "leader.user",
    email: "leader@ims.com",
    password: "leader123",
    role: "Leader",
    status: "Active",
    fullName: "Team Leader",
    createdAt: "2025-01-18",
  },
  {
    id: 6,
    username: "worker.user",
    email: "worker@ims.com",
    password: "worker123",
    role: "Worker",
    status: "Active",
    fullName: "John Worker",
    createdAt: "2025-01-20",
  },
];

// Role permissions
export const rolePermissions = {
  Admin: ["dashboard", "users", "settings", "reports", "inventory", "orders"],
  Manager: ["dashboard", "reports", "inventory", "orders", "scheduling"],
  Leader: ["dashboard", "tasks", "employees"],
  Worker: ["my-tasks"],
  Sales: ["dashboard", "orders", "inventory"],
  Planner: ["dashboard", "inventory", "reports"],
};
