spring:
  datasource:
    url: jdbc:postgresql://yamanote.proxy.rlwy.net:57879/railway
    username: postgres
    password: zAghXDygkxzsfGfItOcVCjqkqKrCCGKu
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

  data:
    redis:
      host: ${REDIS_HOST}
      port: 6379
      username: default
      password: ${REDIS_PASSWORD}
      ssl:
        enabled: true
  mail:
    host: email-smtp.<ap-southeast-1>.amazonaws.com
    port: 587
    username: ${SES_SMTP_USERNAME}
    password: ${SES_SMTP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

aws:
  region: ap-southeast-1
  sns-topic-arn: arn:aws:sns:ap-southeast-1:638389534958:ims-sns
  sqs-queue-url: https://sqs.ap-southeast-1.amazonaws.com/638389534958/ims-queue
  bucket-name: ims-stores

jwt:
  secret: ${JWT_SECRET_KEY}
  expiration: 1800000
  refresh-expiration: 14400000

ai:
  provider: openai
  openai:
    api-key: ${OPENAI_API_KEY}
    url: https://api.openai.com/v1/chat/completions
    model: gpt-4o-mini
    max-tokens: 500
    temperature: 0.3

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: INFO

app:
  mail:
    from: no-reply@your-domain.com
