server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://yamanote.proxy.rlwy.net:57879/railway
    username: postgres
    password: zAghXDygkxzsfGfItOcVCjqkqKrCCGKu
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  flyway:
    enabled: false
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: false
    repair-on-migrate: true

  data:
    redis:
      host: evolving-muskox-40304.upstash.io
      port: 6379
      username: default
      password: AZ1wAAIncDJkNWQ4OGMzODA3ODI0NDQyOGJiZDhjNmY2MzZiNTg4MXAyNDAzMDQ
      ssl:
        enabled: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ims.internal.system@gmail.com
    password: dtsg mmii gsrb wcny
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

aws:
  access-key: AKIAZJIX3IDXPSHJWQ3B
  secret-key: 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
  region: ap-southeast-1
  bucket-name: ims-stores

jwt:
  secret: myVeryVeryVeryVeryVeryVerySecretKey1234567890
  expiration: 28800000
  refresh-expiration: 86400000

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: INFO
